# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "http://test/"
  ignore:
#    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*
    - !!js/regexp ^#f-.*
#    - !!js/regexp .menu.dropdown
#    - !!js/regexp .dropdown.menu
#    - !!js/regexp .slide-(in|out)-(right|left).*
  # Gulp will reference these paths when it copies files
ZURB: "../../zurb/"
# What input - optional
WI:
#  - "what-input.js"
#  - "what-input.min.js"
JS:  
  - "foundation.core.js"
  - "foundation.util.*.js"
#  - "foundation.util.mediaQuery.js"
#  - "foundation.util.box.js"
#  - "foundation.util.keyboard.js"
#  - "foundation.util.motion.js"
#  - "foundation.util.nest.js"
#  - "foundation.util.timerAndImageLoader.js"
#  - "foundation.util.touch.js"
#  - "foundation.util.triggers.js"
  # Individual Foundation components
  # If you aren't using a component, just remove it from the list
#  - "foundation.abide.js"
#  - "foundation.accordion.js"
#  - "foundation.accordionMenu.js"
#  - "foundation.drilldown.js"
#  - "foundation.dropdown.js"
#  - "foundation.dropdownMenu.js"
#  - "foundation.equalizer.js"
#  - "foundation.interchange.js"
#  - "foundation.magellan.js"
#  - "foundation.offcanvas.js"
#  - "foundation.orbit.js"
  - "foundation.responsiveMenu.js"
#  - "foundation.responsiveToggle.js"
#  - "foundation.reveal.js"
#  - "foundation.slider.js"
#  - "foundation.sticky.js"
#  - "foundation.tabs.js"
#  - "foundation.toggler.js"
#  - "foundation.tooltip.js"
FONT: 
# - "fi-address-book.svg"
# - "fi-alert.svg"
# - "fi-align-center.svg"
# - "fi-align-justify.svg"
# - "fi-align-left.svg"
# - "fi-align-right.svg"
# - "fi-anchor.svg"
# - "fi-annotate.svg"
# - "fi-archive.svg"
# - "fi-arrow-down.svg"
# - "fi-arrow-left.svg"
# - "fi-arrow-right.svg"
# - "fi-arrows-compress.svg"
# - "fi-arrows-expand.svg"
# - "fi-arrows-in.svg"
# - "fi-arrows-out.svg"
# - "fi-arrow-up.svg"
# - "fi-asl.svg"
# - "fi-asterisk.svg"
# - "fi-at-sign.svg"
# - "fi-background-color.svg"
# - "fi-battery-empty.svg"
# - "fi-battery-full.svg"
# - "fi-battery-half.svg"
# - "fi-bitcoin-circle.svg"
# - "fi-bitcoin.svg"
# - "fi-blind.svg"
# - "fi-bluetooth.svg"
# - "fi-bold.svg"
# - "fi-book-bookmark.svg"
# - "fi-bookmark.svg"
# - "fi-book.svg"
# - "fi-braille.svg"
# - "fi-burst-new.svg"
# - "fi-burst-sale.svg"
# - "fi-burst.svg"
# - "fi-calendar.svg"
# - "fi-camera.svg"
# - "fi-checkbox.svg"
# - "fi-check.svg"
# - "fi-clipboard-notes.svg"
# - "fi-clipboard-pencil.svg"
# - "fi-clipboard.svg"
# - "fi-clock.svg"
# - "fi-closed-caption.svg"
# - "fi-cloud.svg"
# - "fi-comment-minus.svg"
# - "fi-comment-quotes.svg"
# - "fi-comments.svg"
# - "fi-comment.svg"
# - "fi-comment-video.svg"
# - "fi-compass.svg"
# - "fi-contrast.svg"
# - "fi-credit-card.svg"
# - "fi-crop.svg"
# - "fi-crown.svg"
# - "fi-css3.svg"
# - "fi-database.svg"
# - "fi-die-five.svg"
# - "fi-die-four.svg"
# - "fi-die-one.svg"
# - "fi-die-six.svg"
# - "fi-die-three.svg"
# - "fi-die-two.svg"
# - "fi-dislike.svg"
# - "fi-dollar-bill.svg"
# - "fi-dollar.svg"
# - "fi-download.svg"
# - "fi-eject.svg"
# - "fi-elevator.svg"
# - "fi-euro.svg"
# - "fi-eye.svg"
# - "fi-fast-forward.svg"
# - "fi-female.svg"
# - "fi-female-symbol.svg"
# - "fi-filter.svg"
# - "fi-first-aid.svg"
# - "fi-flag.svg"
# - "fi-folder-add.svg"
# - "fi-folder-lock.svg"
# - "fi-folder.svg"
# - "fi-foot.svg"
# - "fi-foundation.svg"
# - "fi-graph-bar.svg"
# - "fi-graph-horizontal.svg"
# - "fi-graph-pie.svg"
# - "fi-graph-trend.svg"
# - "fi-guide-dog.svg"
# - "fi-hearing-aid.svg"
# - "fi-heart.svg"
# - "fi-home.svg"
# - "fi-html5.svg"
# - "fi-indent-less.svg"
# - "fi-indent-more.svg"
# - "fi-info.svg"
# - "fi-italic.svg"
# - "fi-key.svg"
# - "fi-laptop.svg"
# - "fi-layout.svg"
# - "fi-lightbulb.svg"
# - "fi-like.svg"
# - "fi-link.svg"
# - "fi-list-bullet.svg"
# - "fi-list-number.svg"
# - "fi-list.svg"
# - "fi-list-thumbnails.svg"
# - "fi-lock.svg"
# - "fi-loop.svg"
 - "fi-magnifying-glass.svg"
 - "fi-mail.svg"
# - "fi-male-female.svg"
# - "fi-male.svg"
# - "fi-male-symbol.svg"
# - "fi-map.svg"
# - "fi-marker.svg"
# - "fi-megaphone.svg"
# - "fi-microphone.svg"
# - "fi-minus-circle.svg"
# - "fi-minus.svg"
# - "fi-mobile-signal.svg"
# - "fi-mobile.svg"
# - "fi-monitor.svg"
# - "fi-mountains.svg"
# - "fi-music.svg"
# - "fi-next.svg"
# - "fi-no-dogs.svg"
# - "fi-no-smoking.svg"
# - "fi-page-add.svg"
# - "fi-page-copy.svg"
# - "fi-page-csv.svg"
# - "fi-page-delete.svg"
# - "fi-page-doc.svg"
# - "fi-page-edit.svg"
# - "fi-page-export-csv.svg"
# - "fi-page-export-doc.svg"
# - "fi-page-export-pdf.svg"
# - "fi-page-export.svg"
# - "fi-page-filled.svg"
# - "fi-page-multiple.svg"
# - "fi-page-pdf.svg"
# - "fi-page-remove.svg"
# - "fi-page-search.svg"
# - "fi-page.svg"
# - "fi-paint-bucket.svg"
# - "fi-paperclip.svg"
# - "fi-pause.svg"
# - "fi-paw.svg"
# - "fi-paypal.svg"
# - "fi-pencil.svg"
# - "fi-photo.svg"
# - "fi-play-circle.svg"
# - "fi-play.svg"
# - "fi-play-video.svg"
# - "fi-plus.svg"
# - "fi-pound.svg"
# - "fi-power.svg"
# - "fi-previous.svg"
# - "fi-pricetag-multiple.svg"
# - "fi-price-tag.svg"
# - "fi-print.svg"
# - "fi-prohibited.svg"
# - "fi-projection-screen.svg"
# - "fi-puzzle.svg"
# - "fi-quote.svg"
# - "fi-record.svg"
# - "fi-refresh.svg"
# - "fi-results-demographics.svg"
# - "fi-results.svg"
# - "fi-rewind.svg"
# - "fi-rewind-ten.svg"
# - "fi-rss.svg"
# - "fi-safety-cone.svg"
# - "fi-save.svg"
# - "fi-share.svg"
# - "fi-sheriff-badge.svg"
# - "fi-shield.svg"
# - "fi-shopping-bag.svg"
# - "fi-shopping-cart.svg"
# - "fi-shuffle.svg"
# - "fi-skull.svg"
# - "fi-social-500px.svg"
# - "fi-social-adobe.svg"
# - "fi-social-amazon.svg"
# - "fi-social-android.svg"
# - "fi-social-apple.svg"
# - "fi-social-behance.svg"
# - "fi-social-bing.svg"
# - "fi-social-blogger.svg"
# - "fi-social-delicious.svg"
# - "fi-social-designer-news.svg"
# - "fi-social-deviant-art.svg"
# - "fi-social-digg.svg"
# - "fi-social-dribbble.svg"
# - "fi-social-drive.svg"
# - "fi-social-dropbox.svg"
# - "fi-social-evernote.svg"
# - "fi-social-facebook.svg"
# - "fi-social-flickr.svg"
# - "fi-social-forrst.svg"
# - "fi-social-foursquare.svg"
# - "fi-social-game-center.svg"
# - "fi-social-github.svg"
# - "fi-social-google-plus.svg"
# - "fi-social-hacker-news.svg"
# - "fi-social-hi5.svg"
# - "fi-social-instagram.svg"
# - "fi-social-joomla.svg"
# - "fi-social-lastfm.svg"
# - "fi-social-linkedin.svg"
# - "fi-social-medium.svg"
# - "fi-social-myspace.svg"
# - "fi-social-orkut.svg"
# - "fi-social-path.svg"
# - "fi-social-picasa.svg"
# - "fi-social-pinterest.svg"
# - "fi-social-rdio.svg"
# - "fi-social-reddit.svg"
# - "fi-social-skillshare.svg"
# - "fi-social-skype.svg"
# - "fi-social-smashing-mag.svg"
# - "fi-social-snapchat.svg"
# - "fi-social-spotify.svg"
# - "fi-social-squidoo.svg"
# - "fi-social-stack-overflow.svg"
# - "fi-social-steam.svg"
# - "fi-social-stumbleupon.svg"
# - "fi-social-treehouse.svg"
# - "fi-social-tumblr.svg"
# - "fi-social-twitter.svg"
# - "fi-social-vimeo.svg"
# - "fi-social-windows.svg"
# - "fi-social-xbox.svg"
# - "fi-social-yahoo.svg"
# - "fi-social-yelp.svg"
# - "fi-social-youtube.svg"
# - "fi-social-zerply.svg"
# - "fi-social-zurb.svg"
# - "fi-sound.svg"
# - "fi-star.svg"
# - "fi-stop.svg"
# - "fi-strikethrough.svg"
# - "fi-subscript.svg"
# - "fi-superscript.svg"
# - "fi-tablet-landscape.svg"
# - "fi-tablet-portrait.svg"
# - "fi-target.svg"
# - "fi-target-two.svg"
# - "fi-telephone-accessible.svg"
# - "fi-telephone.svg"
# - "fi-text-color.svg"
# - "fi-thumbnails.svg"
# - "fi-ticket.svg"
# - "fi-torso-business.svg"
# - "fi-torso-female.svg"
# - "fi-torsos-all-female.svg"
# - "fi-torsos-all.svg"
# - "fi-torsos-female-male.svg"
# - "fi-torsos-male-female.svg"
# - "fi-torsos.svg"
# - "fi-torso.svg"
# - "fi-trash.svg"
# - "fi-trees.svg"
# - "fi-trophy.svg"
# - "fi-underline.svg"
# - "fi-universal-access.svg"
# - "fi-unlink.svg"
# - "fi-unlock.svg"
# - "fi-upload-cloud.svg"
# - "fi-upload.svg"
# - "fi-usb.svg"
# - "fi-video.svg"
# - "fi-volume-none.svg"
# - "fi-volume-strike.svg"
# - "fi-volume.svg"
# - "fi-web.svg"
# - "fi-wheelchair.svg"
# - "fi-widget.svg"
# - "fi-wrench.svg"
# - "fi-x-circle.svg"
# - "fi-x.svg"
# - "fi-yen.svg"
# - "fi-zoom-in.svg"
# - "fi-zoom-out.svg"